package com.alienforce.utils;

import java.util.List;

public final class Constants {

    public static final int WIDTH = 1500;
    public static final int HEIGHT = 900;
    public static final int BUTTON_WIDTH = 200;
    public static final int BUTTON_HEIGHT = 50;
    public static final int FPS = 60;
    public static final int FRAME_DELAY = 1000 / FPS;
    public static final double ASTEROID_OFFSET = 50;
    // how far outside the screen asteroids spawn
    public static final double MIDDLE_X = (double) WIDTH / 2;
    public static final double MIDDLE_Y = (double) HEIGHT / 2;
    public static final int SPAWN_DELAY = 1000;
    public static final double ASTEROID_SPEED = 3;
    public static final double MAX_PLAYER_SPEED = 5;
    public static final double PLAYER_ACCELERATION = 0.2;
    public static final double ROTATION_SPEED = 0.06;
    public static final double PLAYER_VELOCITY_DECAY = 0.98;
    public static final List<GameLevel> GAME_LEVELS = List.of(
<<<<<<< Updated upstream
        GameLevel
            .builder()
            .LEVEL_NUMBER(0)
            .PLAYER_BULLET_SPEED(16)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(15)
            .ALIEN_SPEED(1.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(150)
            .ALIEN_SPAWN_DELAY(15000)
            .ALIEN_SPAWN_INITIAL_DELAY(5000)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(4)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(1)
            .PLAYER_BULLET_SPEED(16)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(12)
            .ALIEN_SPEED(1.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(150)
            .ALIEN_SPAWN_DELAY(7500)
            .ALIEN_SPAWN_INITIAL_DELAY(2500)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(4)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(2)
            .PLAYER_BULLET_SPEED(20)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(10)
            .ALIEN_SPEED(1.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(150)
            .ALIEN_SPAWN_DELAY(7500)
            .ALIEN_SPAWN_INITIAL_DELAY(2500)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(4)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(3)
            .PLAYER_BULLET_SPEED(20)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(9)
            .ALIEN_SPEED(1.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(150)
            .ALIEN_SPAWN_DELAY(1000)
            .ALIEN_SPAWN_INITIAL_DELAY(1000)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(4)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(4)
            .PLAYER_BULLET_SPEED(25)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(8)
            .ALIEN_SPEED(1.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(150)
            .ALIEN_SPAWN_DELAY(500)
            .ALIEN_SPAWN_INITIAL_DELAY(500)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(5)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(5)
            .PLAYER_BULLET_SPEED(30)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(7)
            .ALIEN_SPEED(1.1)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(100)
            .ALIEN_SPAWN_DELAY(500)
            .ALIEN_SPAWN_INITIAL_DELAY(500)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(5)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(6)
            .PLAYER_BULLET_SPEED(35)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(6)
            .ALIEN_SPEED(1.6)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(70)
            .ALIEN_SPAWN_DELAY(400)
            .ALIEN_SPAWN_INITIAL_DELAY(400)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(5)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(7)
            .PLAYER_BULLET_SPEED(40)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(5)
            .ALIEN_SPEED(1.7)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(70)
            .ALIEN_SPAWN_DELAY(400)
            .ALIEN_SPAWN_INITIAL_DELAY(400)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(6)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(8)
            .PLAYER_BULLET_SPEED(45)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(5)
            .ALIEN_SPEED(1.8)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(70)
            .ALIEN_SPAWN_DELAY(350)
            .ALIEN_SPAWN_INITIAL_DELAY(350)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(6)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(9)
            .PLAYER_BULLET_SPEED(50)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(4)
            .ALIEN_SPEED(2.0)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(70)
            .ALIEN_SPAWN_DELAY(325)
            .ALIEN_SPAWN_INITIAL_DELAY(325)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(7)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(10)
            .PLAYER_BULLET_SPEED(80)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(4)
            .ALIEN_SPEED(2.2)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(65)
            .ALIEN_SPAWN_DELAY(325)
            .ALIEN_SPAWN_INITIAL_DELAY(325)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(7)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(11)
            .PLAYER_BULLET_SPEED(100)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(4)
            .ALIEN_SPEED(2.3)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(65)
            .ALIEN_SPAWN_DELAY(325)
            .ALIEN_SPAWN_INITIAL_DELAY(325)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(7)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(12)
            .PLAYER_BULLET_SPEED(120)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(4)
            .ALIEN_SPEED(2.4)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(50)
            .ALIEN_SPAWN_DELAY(325)
            .ALIEN_SPAWN_INITIAL_DELAY(325)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(45)
            .ALIEN_BULLET_SPEED(7)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build(),
        GameLevel
            .builder()
            .LEVEL_NUMBER(13)
            .PLAYER_BULLET_SPEED(140)
            .PLAYER_SHOOT_COOLDOWN_FRAMES(3)
            .ALIEN_SPEED(2.5)
            .ALIEN_SHOOT_COOLDOWN_FRAMES(40)
            .ALIEN_SPAWN_DELAY(325)
            .ALIEN_SPAWN_INITIAL_DELAY(325)
            .ALIEN_SPAWN_NO_SHOOT_FRAMES(40)
            .ALIEN_BULLET_SPEED(7)
            .ALIEN_TARGET_UPDATE_INTERVAL(45)
            .build()
=======
            GameLevel
                    .builder()
                    .levelNumber(0)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(15)
                                    .bulletSpeed(16)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(150)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(4)
                                                    .build()
                                    )
                                    .speed(1.0)
                                    .spawnDelay(15000)
                                    .spawnInitialDelay(5000)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(1)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(12)
                                    .bulletSpeed(16)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(150)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(4)
                                                    .build()
                                    )
                                    .speed(1.0)
                                    .spawnDelay(7500)
                                    .spawnInitialDelay(2500)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(2)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(10)
                                    .bulletSpeed(20)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(150)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(4)
                                                    .build()
                                    )
                                    .speed(1.0)
                                    .spawnDelay(7500)
                                    .spawnInitialDelay(2500)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(3)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(9)
                                    .bulletSpeed(20)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(150)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(4)
                                                    .build()
                                    )
                                    .speed(1.0)
                                    .spawnDelay(1000)
                                    .spawnInitialDelay(1000)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(4)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(8)
                                    .bulletSpeed(25)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(150)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(5)
                                                    .build()
                                    )
                                    .speed(1.0)
                                    .spawnDelay(500)
                                    .spawnInitialDelay(500)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(5)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(7)
                                    .bulletSpeed(30)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(100)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(5)
                                                    .build()
                                    )
                                    .speed(1.1)
                                    .spawnDelay(500)
                                    .spawnInitialDelay(500)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(6)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(6)
                                    .bulletSpeed(35)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(70)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(5)
                                                    .build()
                                    )
                                    .speed(1.6)
                                    .spawnDelay(400)
                                    .spawnInitialDelay(400)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(7)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(5)
                                    .bulletSpeed(40)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(70)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(6)
                                                    .build()
                                    )
                                    .speed(1.7)
                                    .spawnDelay(400)
                                    .spawnInitialDelay(400)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(8)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(5)
                                    .bulletSpeed(45)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(70)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(6)
                                                    .build()
                                    )
                                    .speed(1.8)
                                    .spawnDelay(350)
                                    .spawnInitialDelay(350)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(9)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(4)
                                    .bulletSpeed(50)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(70)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.0)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(10)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(4)
                                    .bulletSpeed(80)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(65)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.2)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(11)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(4)
                                    .bulletSpeed(100)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(65)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.3)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(12)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(4)
                                    .bulletSpeed(120)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(50)
                                                    .spawnNoShootFrames(45)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.4)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(13)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(2)
                                    .bulletSpeed(140)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(40)
                                                    .spawnNoShootFrames(40)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.5)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build(),
            GameLevel
                    .builder()
                    .levelNumber(14)
                    .playerShootConstants(
                            ShootConstants
                                    .builder()
                                    .shootCooldownFrames(1)
                                    .bulletSpeed(60)
                                    .build()
                    )
                    .alien(
                            AlienConstants
                                    .builder()
                                    .shootConstants(
                                            ShootConstants
                                                    .builder()
                                                    .shootCooldownFrames(20)
                                                    .spawnNoShootFrames(40)
                                                    .bulletSpeed(7)
                                                    .build()
                                    )
                                    .speed(2.5)
                                    .spawnDelay(325)
                                    .spawnInitialDelay(325)
                                    .targetUpdateInterval(45)
                                    .build()
                    )
                    .build()
>>>>>>> Stashed changes
    );
    public static final int ALIEN_KILL_SCORE = 5;

    private Constants() {
    }
}
